/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.catalina.security;

import org.junit.Test;

public class TestSecurityClassLoad {

    @Test
    public void testLoad() throws Exception {
        // Note that this will fail if you run it from within Eclipse. This is
        // because one of the loaded classes (AccessLogValve$3) is a synthetic
        // class generated by javac but not by the JDT compiler. Behaviour with
        // other IDEs is currently unknown.
        SecurityClassLoad.securityClassLoad(
            Thread.currentThread().getContextClassLoader(), false);
    }
}
