/* Generated By:JavaCC: Do not edit this line. HttpParserTreeConstants.java Version 5.0 */
package org.apache.tomcat.util.http.parser;

public interface HttpParserTreeConstants
{
  public int JJTMEDIATYPE = 0;
  public int JJTTYPE = 1;
  public int JJTSUBTYPE = 2;
  public int JJTPARAMETER = 3;
  public int JJTATTRIBUTE = 4;
  public int JJTVALUE = 5;


  public String[] jjtNodeName = {
    "MediaType",
    "Type",
    "SubType",
    "Parameter",
    "Attribute",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=f4745df783771bdbdddd3be661f1c089 (do not edit this line) */
