/* Generated By:JavaCC: Do not edit this line. ELParserTreeConstants.java Version 7.0.13 */
package org.apache.el.parser;

public interface ELParserTreeConstants {
    int JJTCOMPOSITEEXPRESSION = 0;
    int JJTLITERALEXPRESSION = 1;
    int JJTDEFERREDEXPRESSION = 2;
    int JJTDYNAMICEXPRESSION = 3;
    int JJTVOID = 4;
    int JJTSEMICOLON = 5;
    int JJTASSIGN = 6;
    int JJTLAMBDAEXPRESSION = 7;
    int JJTLAMBDAPARAMETERS = 8;
    int JJTELVIS = 9;
    int JJTCHOICE = 10;
    int JJTOR = 11;
    int JJTAND = 12;
    int JJTEQUAL = 13;
    int JJTNOTEQUAL = 14;
    int JJTLESSTHAN = 15;
    int JJTGREATERTHAN = 16;
    int JJTLESSTHANEQUAL = 17;
    int JJTGREATERTHANEQUAL = 18;
    int JJTCONCATENATION = 19;
    int JJTPLUS = 20;
    int JJTMINUS = 21;
    int JJTMULT = 22;
    int JJTDIV = 23;
    int JJTMOD = 24;
    int JJTNEGATIVE = 25;
    int JJTNOTEMPTY = 26;
    int JJTNOT = 27;
    int JJTEMPTY = 28;
    int JJTVALUE = 29;
    int JJTDOTSUFFIX = 30;
    int JJTBRACKETSUFFIX = 31;
    int JJTMETHODPARAMETERS = 32;
    int JJTSETDATA = 33;
    int JJTLISTDATA = 34;
    int JJTMAPDATA = 35;
    int JJTMAPENTRY = 36;
    int JJTIDENTIFIER = 37;
    int JJTFUNCTION = 38;
    int JJTTRUE = 39;
    int JJTFALSE = 40;
    int JJTFLOATINGPOINT = 41;
    int JJTINTEGER = 42;
    int JJTSTRING = 43;
    int JJTNULL = 44;


    String[] jjtNodeName = { "CompositeExpression", "LiteralExpression", "DeferredExpression", "DynamicExpression",
            "void", "Semicolon", "Assign", "LambdaExpression", "LambdaParameters", "Elvis", "Choice", "Or", "And",
            "Equal", "NotEqual", "LessThan", "GreaterThan", "LessThanEqual", "GreaterThanEqual", "Concatenation",
            "Plus", "Minus", "Mult", "Div", "Mod", "Negative", "NotEmpty", "Not", "Empty", "Value", "DotSuffix",
            "BracketSuffix", "MethodParameters", "SetData", "ListData", "MapData", "MapEntry", "Identifier", "Function",
            "True", "False", "FloatingPoint", "Integer", "String", "Null", };
}
/* JavaCC - OriginalChecksum=bf490de1f9b26486497de3154abf559e (do not edit this line) */
