/*
 *  Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.apache.tomcat.addons;

import javax.servlet.Servlet;
import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;

/** 
 * Mapps a templating name ( like a jsp file ) to a class name 
 * generated by the template compiler.
 * 
 * This class is needed at runtime to support *.jsp mappings
 * or <jsp-file> - can be used to support other formats. 
 * 
 * The UserTemplateCompiler is only needed to support run-time
 * compilation - if ahead-of-time compilation is used 
 * all generated files can be mapped explicitly with  
 * <servlet><class-name>.
 * 
 * @author Costin Manolache
 */
public interface UserTemplateClassMapper {

    /**
     * Generate and load the proxy corresponding to the template file.
     *  
     */
    public Servlet loadProxy(String jspFile, 
                             ServletContext ctx, 
                             ServletConfig config) throws ServletException;

    /**
     * Quick check if the template ( or deps ) has been modified
     * and the servlet needs to be regenerated;  
     */
    public boolean needsReload(String jspFile, Servlet s);
}
