/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$29 {

    static final FunctionDescriptor d2i_OCSP_RESPONSE$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle d2i_OCSP_RESPONSE$MH = RuntimeHelper.downcallHandle(
        "d2i_OCSP_RESPONSE",
        constants$29.d2i_OCSP_RESPONSE$FUNC, false
    );
    static final FunctionDescriptor OCSP_CERTID_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle OCSP_CERTID_free$MH = RuntimeHelper.downcallHandle(
        "OCSP_CERTID_free",
        constants$29.OCSP_CERTID_free$FUNC, false
    );
    static final FunctionDescriptor OCSP_REQUEST_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle OCSP_REQUEST_new$MH = RuntimeHelper.downcallHandle(
        "OCSP_REQUEST_new",
        constants$29.OCSP_REQUEST_new$FUNC, false
    );
    static final FunctionDescriptor OCSP_REQUEST_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle OCSP_REQUEST_free$MH = RuntimeHelper.downcallHandle(
        "OCSP_REQUEST_free",
        constants$29.OCSP_REQUEST_free$FUNC, false
    );
    static final FunctionDescriptor i2d_OCSP_REQUEST$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle i2d_OCSP_REQUEST$MH = RuntimeHelper.downcallHandle(
        "i2d_OCSP_REQUEST",
        constants$29.i2d_OCSP_REQUEST$FUNC, false
    );
    static final MemorySegment OPENSSL_FILE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("/tmp/jextract$7507082841068085766.h");
}


