/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$4 {

    static final FunctionDescriptor BIO_new_bio_pair$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_LONG,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle BIO_new_bio_pair$MH = RuntimeHelper.downcallHandle(
        "BIO_new_bio_pair",
        constants$4.BIO_new_bio_pair$FUNC, false
    );
    static final FunctionDescriptor BN_new$FUNC = FunctionDescriptor.of(ADDRESS);
    static final MethodHandle BN_new$MH = RuntimeHelper.downcallHandle(
        "BN_new",
        constants$4.BN_new$FUNC, false
    );
    static final FunctionDescriptor BN_set_word$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle BN_set_word$MH = RuntimeHelper.downcallHandle(
        "BN_set_word",
        constants$4.BN_set_word$FUNC, false
    );
    static final FunctionDescriptor BN_get_rfc2409_prime_768$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle BN_get_rfc2409_prime_768$MH = RuntimeHelper.downcallHandle(
        "BN_get_rfc2409_prime_768",
        constants$4.BN_get_rfc2409_prime_768$FUNC, false
    );
    static final FunctionDescriptor BN_get_rfc2409_prime_1024$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle BN_get_rfc2409_prime_1024$MH = RuntimeHelper.downcallHandle(
        "BN_get_rfc2409_prime_1024",
        constants$4.BN_get_rfc2409_prime_1024$FUNC, false
    );
    static final FunctionDescriptor BN_get_rfc3526_prime_1536$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle BN_get_rfc3526_prime_1536$MH = RuntimeHelper.downcallHandle(
        "BN_get_rfc3526_prime_1536",
        constants$4.BN_get_rfc3526_prime_1536$FUNC, false
    );
}


