/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$25 {

    static final FunctionDescriptor ERR_clear_error$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle ERR_clear_error$MH = RuntimeHelper.downcallHandle(
        "ERR_clear_error",
        constants$25.ERR_clear_error$FUNC, false
    );
    static final FunctionDescriptor ERR_error_string$FUNC = FunctionDescriptor.of(ADDRESS,
        JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle ERR_error_string$MH = RuntimeHelper.downcallHandle(
        "ERR_error_string",
        constants$25.ERR_error_string$FUNC, false
    );
    static final FunctionDescriptor PKCS12_verify_mac$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle PKCS12_verify_mac$MH = RuntimeHelper.downcallHandle(
        "PKCS12_verify_mac",
        constants$25.PKCS12_verify_mac$FUNC, false
    );
    static final FunctionDescriptor PKCS12_free$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS
    );
    static final MethodHandle PKCS12_free$MH = RuntimeHelper.downcallHandle(
        "PKCS12_free",
        constants$25.PKCS12_free$FUNC, false
    );
    static final FunctionDescriptor PKCS12_parse$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle PKCS12_parse$MH = RuntimeHelper.downcallHandle(
        "PKCS12_parse",
        constants$25.PKCS12_parse$FUNC, false
    );
    static final FunctionDescriptor d2i_PKCS12_bio$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle d2i_PKCS12_bio$MH = RuntimeHelper.downcallHandle(
        "d2i_PKCS12_bio",
        constants$25.d2i_PKCS12_bio$FUNC, false
    );
}


