/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class openssl_h  {

    /* package-private */ openssl_h() {}
    public static OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;
    public static int BIO_CLOSE() {
        return (int)1L;
    }
    public static int BIO_CTRL_RESET() {
        return (int)1L;
    }
    public static int BIO_FP_READ() {
        return (int)2L;
    }
    public static int BIO_C_SET_FILENAME() {
        return (int)108L;
    }
    public static int NID_info_access() {
        return (int)177L;
    }
    public static int X509_FILETYPE_PEM() {
        return (int)1L;
    }
    public static int X509_L_FILE_LOAD() {
        return (int)1L;
    }
    public static int X509_L_ADD_DIR() {
        return (int)2L;
    }
    public static int X509_V_OK() {
        return (int)0L;
    }
    public static int X509_V_ERR_CRL_HAS_EXPIRED() {
        return (int)12L;
    }
    public static int X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT() {
        return (int)18L;
    }
    public static int X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN() {
        return (int)19L;
    }
    public static int X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY() {
        return (int)20L;
    }
    public static int X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE() {
        return (int)21L;
    }
    public static int X509_V_ERR_CERT_UNTRUSTED() {
        return (int)27L;
    }
    public static int X509_V_ERR_APPLICATION_VERIFICATION() {
        return (int)50L;
    }
    public static int X509_V_FLAG_CRL_CHECK() {
        return (int)4L;
    }
    public static int X509_V_FLAG_CRL_CHECK_ALL() {
        return (int)8L;
    }
    public static int PEM_R_NO_START_LINE() {
        return (int)108L;
    }
    public static int SSL3_VERSION() {
        return (int)768L;
    }
    public static int TLS1_VERSION() {
        return (int)769L;
    }
    public static int TLS1_1_VERSION() {
        return (int)770L;
    }
    public static int TLS1_2_VERSION() {
        return (int)771L;
    }
    public static int TLS1_3_VERSION() {
        return (int)772L;
    }
    public static int SSL_SENT_SHUTDOWN() {
        return (int)1L;
    }
    public static int SSL_RECEIVED_SHUTDOWN() {
        return (int)2L;
    }
    public static int SSL_OP_SINGLE_ECDH_USE() {
        return (int)0L;
    }
    public static int SSL_OP_SINGLE_DH_USE() {
        return (int)0L;
    }
    public static int SSL_OP_NO_SSLv2() {
        return (int)0L;
    }
    public static int SSL_CONF_FLAG_FILE() {
        return (int)2L;
    }
    public static int SSL_CONF_FLAG_SERVER() {
        return (int)8L;
    }
    public static int SSL_CONF_FLAG_SHOW_ERRORS() {
        return (int)16L;
    }
    public static int SSL_CONF_FLAG_CERTIFICATE() {
        return (int)32L;
    }
    public static int SSL_CONF_TYPE_UNKNOWN() {
        return (int)0L;
    }
    public static int SSL_CONF_TYPE_FILE() {
        return (int)2L;
    }
    public static int SSL_CONF_TYPE_DIR() {
        return (int)3L;
    }
    public static int SSL_SESS_CACHE_OFF() {
        return (int)0L;
    }
    public static int SSL_SESS_CACHE_SERVER() {
        return (int)2L;
    }
    public static int SSL2_VERSION() {
        return (int)2L;
    }
    public static int SSL_TLSEXT_ERR_OK() {
        return (int)0L;
    }
    public static int SSL_TLSEXT_ERR_NOACK() {
        return (int)3L;
    }
    public static int SSL_CB_HANDSHAKE_DONE() {
        return (int)32L;
    }
    public static int SSL_VERIFY_NONE() {
        return (int)0L;
    }
    public static int SSL_VERIFY_PEER() {
        return (int)1L;
    }
    public static int SSL_VERIFY_FAIL_IF_NO_PEER_CERT() {
        return (int)2L;
    }
    public static int SSL_ERROR_NONE() {
        return (int)0L;
    }
    public static int SSL_CTRL_SET_TMP_DH() {
        return (int)3L;
    }
    public static int SSL_CTRL_SET_TMP_ECDH() {
        return (int)4L;
    }
    public static int SSL_CTRL_SESS_NUMBER() {
        return (int)20L;
    }
    public static int SSL_CTRL_SESS_CONNECT() {
        return (int)21L;
    }
    public static int SSL_CTRL_SESS_CONNECT_GOOD() {
        return (int)22L;
    }
    public static int SSL_CTRL_SESS_CONNECT_RENEGOTIATE() {
        return (int)23L;
    }
    public static int SSL_CTRL_SESS_ACCEPT() {
        return (int)24L;
    }
    public static int SSL_CTRL_SESS_ACCEPT_GOOD() {
        return (int)25L;
    }
    public static int SSL_CTRL_SESS_ACCEPT_RENEGOTIATE() {
        return (int)26L;
    }
    public static int SSL_CTRL_SESS_HIT() {
        return (int)27L;
    }
    public static int SSL_CTRL_SESS_CB_HIT() {
        return (int)28L;
    }
    public static int SSL_CTRL_SESS_MISSES() {
        return (int)29L;
    }
    public static int SSL_CTRL_SESS_TIMEOUTS() {
        return (int)30L;
    }
    public static int SSL_CTRL_SESS_CACHE_FULL() {
        return (int)31L;
    }
    public static int SSL_CTRL_SET_SESS_CACHE_SIZE() {
        return (int)42L;
    }
    public static int SSL_CTRL_GET_SESS_CACHE_SIZE() {
        return (int)43L;
    }
    public static int SSL_CTRL_SET_SESS_CACHE_MODE() {
        return (int)44L;
    }
    public static int SSL_CTRL_GET_SESS_CACHE_MODE() {
        return (int)45L;
    }
    public static int SSL_CTRL_SET_TLSEXT_TICKET_KEYS() {
        return (int)59L;
    }
    public static int SSL_CTRL_CHAIN_CERT() {
        return (int)89L;
    }
    public static int SSL_CTRL_SET_MIN_PROTO_VERSION() {
        return (int)123L;
    }
    public static int SSL_CTRL_SET_MAX_PROTO_VERSION() {
        return (int)124L;
    }
    public static int OCSP_RESPONSE_STATUS_SUCCESSFUL() {
        return (int)0L;
    }
    public static int V_OCSP_CERTSTATUS_GOOD() {
        return (int)0L;
    }
    public static int V_OCSP_CERTSTATUS_REVOKED() {
        return (int)1L;
    }
    public static int V_OCSP_CERTSTATUS_UNKNOWN() {
        return (int)2L;
    }
    public static MethodHandle OPENSSL_sk_num$MH() {
        return RuntimeHelper.requireNonNull(constants$0.OPENSSL_sk_num$MH,"OPENSSL_sk_num");
    }
    public static int OPENSSL_sk_num ( MemorySegment x0) {
        var mh$ = OPENSSL_sk_num$MH();
        try {
            return (int)mh$.invokeExact(x0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OPENSSL_sk_value$MH() {
        return RuntimeHelper.requireNonNull(constants$0.OPENSSL_sk_value$MH,"OPENSSL_sk_value");
    }
    public static MemorySegment OPENSSL_sk_value ( MemorySegment x0,  int x1) {
        var mh$ = OPENSSL_sk_value$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(x0, x1);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OpenSSL_version_num$MH() {
        return RuntimeHelper.requireNonNull(constants$0.OpenSSL_version_num$MH,"OpenSSL_version_num");
    }
    public static long OpenSSL_version_num () {
        var mh$ = OpenSSL_version_num$MH();
        try {
            return (long)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OpenSSL_version$MH() {
        return RuntimeHelper.requireNonNull(constants$0.OpenSSL_version$MH,"OpenSSL_version");
    }
    public static MemorySegment OpenSSL_version ( int type) {
        var mh$ = OpenSSL_version$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(type);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle CRYPTO_free$MH() {
        return RuntimeHelper.requireNonNull(constants$0.CRYPTO_free$MH,"CRYPTO_free");
    }
    public static void CRYPTO_free ( MemorySegment ptr,  MemorySegment file,  int line) {
        var mh$ = CRYPTO_free$MH();
        try {
            mh$.invokeExact(ptr, file, line);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_ctrl_pending$MH() {
        return RuntimeHelper.requireNonNull(constants$0.BIO_ctrl_pending$MH,"BIO_ctrl_pending");
    }
    public static long BIO_ctrl_pending ( MemorySegment b) {
        var mh$ = BIO_ctrl_pending$MH();
        try {
            return (long)mh$.invokeExact(b);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_s_file$MH() {
        return RuntimeHelper.requireNonNull(constants$1.BIO_s_file$MH,"BIO_s_file");
    }
    public static MemorySegment BIO_s_file () {
        var mh$ = BIO_s_file$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_new_file$MH() {
        return RuntimeHelper.requireNonNull(constants$1.BIO_new_file$MH,"BIO_new_file");
    }
    public static MemorySegment BIO_new_file ( MemorySegment filename,  MemorySegment mode) {
        var mh$ = BIO_new_file$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(filename, mode);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_new$MH() {
        return RuntimeHelper.requireNonNull(constants$1.BIO_new$MH,"BIO_new");
    }
    public static MemorySegment BIO_new ( MemorySegment type) {
        var mh$ = BIO_new$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(type);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_free$MH() {
        return RuntimeHelper.requireNonNull(constants$1.BIO_free$MH,"BIO_free");
    }
    public static int BIO_free ( MemorySegment a) {
        var mh$ = BIO_free$MH();
        try {
            return (int)mh$.invokeExact(a);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_read$MH() {
        return RuntimeHelper.requireNonNull(constants$1.BIO_read$MH,"BIO_read");
    }
    public static int BIO_read ( MemorySegment b,  MemorySegment data,  int dlen) {
        var mh$ = BIO_read$MH();
        try {
            return (int)mh$.invokeExact(b, data, dlen);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_write$MH() {
        return RuntimeHelper.requireNonNull(constants$1.BIO_write$MH,"BIO_write");
    }
    public static int BIO_write ( MemorySegment b,  MemorySegment data,  int dlen) {
        var mh$ = BIO_write$MH();
        try {
            return (int)mh$.invokeExact(b, data, dlen);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_ctrl$MH() {
        return RuntimeHelper.requireNonNull(constants$2.BIO_ctrl$MH,"BIO_ctrl");
    }
    public static long BIO_ctrl ( MemorySegment bp,  int cmd,  long larg,  MemorySegment parg) {
        var mh$ = BIO_ctrl$MH();
        try {
            return (long)mh$.invokeExact(bp, cmd, larg, parg);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_s_mem$MH() {
        return RuntimeHelper.requireNonNull(constants$2.BIO_s_mem$MH,"BIO_s_mem");
    }
    public static MemorySegment BIO_s_mem () {
        var mh$ = BIO_s_mem$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_s_bio$MH() {
        return RuntimeHelper.requireNonNull(constants$2.BIO_s_bio$MH,"BIO_s_bio");
    }
    public static MemorySegment BIO_s_bio () {
        var mh$ = BIO_s_bio$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BIO_new_bio_pair$MH() {
        return RuntimeHelper.requireNonNull(constants$2.BIO_new_bio_pair$MH,"BIO_new_bio_pair");
    }
    public static int BIO_new_bio_pair ( MemorySegment bio1,  long writebuf1,  MemorySegment bio2,  long writebuf2) {
        var mh$ = BIO_new_bio_pair$MH();
        try {
            return (int)mh$.invokeExact(bio1, writebuf1, bio2, writebuf2);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BN_new$MH() {
        return RuntimeHelper.requireNonNull(constants$2.BN_new$MH,"BN_new");
    }
    public static MemorySegment BN_new () {
        var mh$ = BN_new$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BN_set_word$MH() {
        return RuntimeHelper.requireNonNull(constants$2.BN_set_word$MH,"BN_set_word");
    }
    public static int BN_set_word ( MemorySegment a,  long w) {
        var mh$ = BN_set_word$MH();
        try {
            return (int)mh$.invokeExact(a, w);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BN_get_rfc2409_prime_768$MH() {
        return RuntimeHelper.requireNonNull(constants$3.BN_get_rfc2409_prime_768$MH,"BN_get_rfc2409_prime_768");
    }
    public static MemorySegment BN_get_rfc2409_prime_768 ( MemorySegment bn) {
        var mh$ = BN_get_rfc2409_prime_768$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bn);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BN_get_rfc2409_prime_1024$MH() {
        return RuntimeHelper.requireNonNull(constants$3.BN_get_rfc2409_prime_1024$MH,"BN_get_rfc2409_prime_1024");
    }
    public static MemorySegment BN_get_rfc2409_prime_1024 ( MemorySegment bn) {
        var mh$ = BN_get_rfc2409_prime_1024$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bn);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BN_get_rfc3526_prime_1536$MH() {
        return RuntimeHelper.requireNonNull(constants$3.BN_get_rfc3526_prime_1536$MH,"BN_get_rfc3526_prime_1536");
    }
    public static MemorySegment BN_get_rfc3526_prime_1536 ( MemorySegment bn) {
        var mh$ = BN_get_rfc3526_prime_1536$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bn);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BN_get_rfc3526_prime_2048$MH() {
        return RuntimeHelper.requireNonNull(constants$3.BN_get_rfc3526_prime_2048$MH,"BN_get_rfc3526_prime_2048");
    }
    public static MemorySegment BN_get_rfc3526_prime_2048 ( MemorySegment bn) {
        var mh$ = BN_get_rfc3526_prime_2048$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bn);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BN_get_rfc3526_prime_3072$MH() {
        return RuntimeHelper.requireNonNull(constants$3.BN_get_rfc3526_prime_3072$MH,"BN_get_rfc3526_prime_3072");
    }
    public static MemorySegment BN_get_rfc3526_prime_3072 ( MemorySegment bn) {
        var mh$ = BN_get_rfc3526_prime_3072$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bn);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BN_get_rfc3526_prime_4096$MH() {
        return RuntimeHelper.requireNonNull(constants$3.BN_get_rfc3526_prime_4096$MH,"BN_get_rfc3526_prime_4096");
    }
    public static MemorySegment BN_get_rfc3526_prime_4096 ( MemorySegment bn) {
        var mh$ = BN_get_rfc3526_prime_4096$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bn);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BN_get_rfc3526_prime_6144$MH() {
        return RuntimeHelper.requireNonNull(constants$4.BN_get_rfc3526_prime_6144$MH,"BN_get_rfc3526_prime_6144");
    }
    public static MemorySegment BN_get_rfc3526_prime_6144 ( MemorySegment bn) {
        var mh$ = BN_get_rfc3526_prime_6144$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bn);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle BN_get_rfc3526_prime_8192$MH() {
        return RuntimeHelper.requireNonNull(constants$4.BN_get_rfc3526_prime_8192$MH,"BN_get_rfc3526_prime_8192");
    }
    public static MemorySegment BN_get_rfc3526_prime_8192 ( MemorySegment bn) {
        var mh$ = BN_get_rfc3526_prime_8192$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bn);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ASN1_STRING_length$MH() {
        return RuntimeHelper.requireNonNull(constants$4.ASN1_STRING_length$MH,"ASN1_STRING_length");
    }
    public static int ASN1_STRING_length ( MemorySegment x) {
        var mh$ = ASN1_STRING_length$MH();
        try {
            return (int)mh$.invokeExact(x);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ASN1_STRING_get0_data$MH() {
        return RuntimeHelper.requireNonNull(constants$4.ASN1_STRING_get0_data$MH,"ASN1_STRING_get0_data");
    }
    public static MemorySegment ASN1_STRING_get0_data ( MemorySegment x) {
        var mh$ = ASN1_STRING_get0_data$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(x);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle EVP_MD_get0_provider$MH() {
        return RuntimeHelper.requireNonNull(constants$4.EVP_MD_get0_provider$MH,"EVP_MD_get0_provider");
    }
    public static MemorySegment EVP_MD_get0_provider ( MemorySegment md) {
        var mh$ = EVP_MD_get0_provider$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(md);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle EVP_MD_fetch$MH() {
        return RuntimeHelper.requireNonNull(constants$4.EVP_MD_fetch$MH,"EVP_MD_fetch");
    }
    public static MemorySegment EVP_MD_fetch ( MemorySegment ctx,  MemorySegment algorithm,  MemorySegment properties) {
        var mh$ = EVP_MD_fetch$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(ctx, algorithm, properties);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle EVP_MD_free$MH() {
        return RuntimeHelper.requireNonNull(constants$5.EVP_MD_free$MH,"EVP_MD_free");
    }
    public static void EVP_MD_free ( MemorySegment md) {
        var mh$ = EVP_MD_free$MH();
        try {
            mh$.invokeExact(md);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle EVP_PKEY_get_base_id$MH() {
        return RuntimeHelper.requireNonNull(constants$5.EVP_PKEY_get_base_id$MH,"EVP_PKEY_get_base_id");
    }
    public static int EVP_PKEY_get_base_id ( MemorySegment pkey) {
        var mh$ = EVP_PKEY_get_base_id$MH();
        try {
            return (int)mh$.invokeExact(pkey);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle EVP_PKEY_get_bits$MH() {
        return RuntimeHelper.requireNonNull(constants$5.EVP_PKEY_get_bits$MH,"EVP_PKEY_get_bits");
    }
    public static int EVP_PKEY_get_bits ( MemorySegment pkey) {
        var mh$ = EVP_PKEY_get_bits$MH();
        try {
            return (int)mh$.invokeExact(pkey);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle EC_GROUP_free$MH() {
        return RuntimeHelper.requireNonNull(constants$5.EC_GROUP_free$MH,"EC_GROUP_free");
    }
    public static void EC_GROUP_free ( MemorySegment group) {
        var mh$ = EC_GROUP_free$MH();
        try {
            mh$.invokeExact(group);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle EC_GROUP_get_curve_name$MH() {
        return RuntimeHelper.requireNonNull(constants$5.EC_GROUP_get_curve_name$MH,"EC_GROUP_get_curve_name");
    }
    public static int EC_GROUP_get_curve_name ( MemorySegment group) {
        var mh$ = EC_GROUP_get_curve_name$MH();
        try {
            return (int)mh$.invokeExact(group);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle EC_KEY_new_by_curve_name$MH() {
        return RuntimeHelper.requireNonNull(constants$5.EC_KEY_new_by_curve_name$MH,"EC_KEY_new_by_curve_name");
    }
    public static MemorySegment EC_KEY_new_by_curve_name ( int nid) {
        var mh$ = EC_KEY_new_by_curve_name$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(nid);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle EC_KEY_free$MH() {
        return RuntimeHelper.requireNonNull(constants$6.EC_KEY_free$MH,"EC_KEY_free");
    }
    public static void EC_KEY_free ( MemorySegment key) {
        var mh$ = EC_KEY_free$MH();
        try {
            mh$.invokeExact(key);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle DH_new$MH() {
        return RuntimeHelper.requireNonNull(constants$6.DH_new$MH,"DH_new");
    }
    public static MemorySegment DH_new () {
        var mh$ = DH_new$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle DH_free$MH() {
        return RuntimeHelper.requireNonNull(constants$6.DH_free$MH,"DH_free");
    }
    public static void DH_free ( MemorySegment dh) {
        var mh$ = DH_free$MH();
        try {
            mh$.invokeExact(dh);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle DH_set0_pqg$MH() {
        return RuntimeHelper.requireNonNull(constants$6.DH_set0_pqg$MH,"DH_set0_pqg");
    }
    public static int DH_set0_pqg ( MemorySegment dh,  MemorySegment p,  MemorySegment q,  MemorySegment g) {
        var mh$ = DH_set0_pqg$MH();
        try {
            return (int)mh$.invokeExact(dh, p, q, g);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_STORE_set_flags$MH() {
        return RuntimeHelper.requireNonNull(constants$6.X509_STORE_set_flags$MH,"X509_STORE_set_flags");
    }
    public static int X509_STORE_set_flags ( MemorySegment ctx,  long flags) {
        var mh$ = X509_STORE_set_flags$MH();
        try {
            return (int)mh$.invokeExact(ctx, flags);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_STORE_CTX_get0_untrusted$MH() {
        return RuntimeHelper.requireNonNull(constants$6.X509_STORE_CTX_get0_untrusted$MH,"X509_STORE_CTX_get0_untrusted");
    }
    public static MemorySegment X509_STORE_CTX_get0_untrusted ( MemorySegment ctx) {
        var mh$ = X509_STORE_CTX_get0_untrusted$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_STORE_add_lookup$MH() {
        return RuntimeHelper.requireNonNull(constants$7.X509_STORE_add_lookup$MH,"X509_STORE_add_lookup");
    }
    public static MemorySegment X509_STORE_add_lookup ( MemorySegment v,  MemorySegment m) {
        var mh$ = X509_STORE_add_lookup$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(v, m);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_LOOKUP_hash_dir$MH() {
        return RuntimeHelper.requireNonNull(constants$7.X509_LOOKUP_hash_dir$MH,"X509_LOOKUP_hash_dir");
    }
    public static MemorySegment X509_LOOKUP_hash_dir () {
        var mh$ = X509_LOOKUP_hash_dir$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_LOOKUP_file$MH() {
        return RuntimeHelper.requireNonNull(constants$7.X509_LOOKUP_file$MH,"X509_LOOKUP_file");
    }
    public static MemorySegment X509_LOOKUP_file () {
        var mh$ = X509_LOOKUP_file$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_LOOKUP_ctrl$MH() {
        return RuntimeHelper.requireNonNull(constants$7.X509_LOOKUP_ctrl$MH,"X509_LOOKUP_ctrl");
    }
    public static int X509_LOOKUP_ctrl ( MemorySegment ctx,  int cmd,  MemorySegment argc,  long argl,  MemorySegment ret) {
        var mh$ = X509_LOOKUP_ctrl$MH();
        try {
            return (int)mh$.invokeExact(ctx, cmd, argc, argl, ret);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_STORE_CTX_get_ex_data$MH() {
        return RuntimeHelper.requireNonNull(constants$7.X509_STORE_CTX_get_ex_data$MH,"X509_STORE_CTX_get_ex_data");
    }
    public static MemorySegment X509_STORE_CTX_get_ex_data ( MemorySegment ctx,  int idx) {
        var mh$ = X509_STORE_CTX_get_ex_data$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(ctx, idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_STORE_CTX_get_error$MH() {
        return RuntimeHelper.requireNonNull(constants$7.X509_STORE_CTX_get_error$MH,"X509_STORE_CTX_get_error");
    }
    public static int X509_STORE_CTX_get_error ( MemorySegment ctx) {
        var mh$ = X509_STORE_CTX_get_error$MH();
        try {
            return (int)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_STORE_CTX_set_error$MH() {
        return RuntimeHelper.requireNonNull(constants$8.X509_STORE_CTX_set_error$MH,"X509_STORE_CTX_set_error");
    }
    public static void X509_STORE_CTX_set_error ( MemorySegment ctx,  int s) {
        var mh$ = X509_STORE_CTX_set_error$MH();
        try {
            mh$.invokeExact(ctx, s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_STORE_CTX_get_error_depth$MH() {
        return RuntimeHelper.requireNonNull(constants$8.X509_STORE_CTX_get_error_depth$MH,"X509_STORE_CTX_get_error_depth");
    }
    public static int X509_STORE_CTX_get_error_depth ( MemorySegment ctx) {
        var mh$ = X509_STORE_CTX_get_error_depth$MH();
        try {
            return (int)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_STORE_CTX_get_current_cert$MH() {
        return RuntimeHelper.requireNonNull(constants$8.X509_STORE_CTX_get_current_cert$MH,"X509_STORE_CTX_get_current_cert");
    }
    public static MemorySegment X509_STORE_CTX_get_current_cert ( MemorySegment ctx) {
        var mh$ = X509_STORE_CTX_get_current_cert$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_STORE_CTX_get0_current_issuer$MH() {
        return RuntimeHelper.requireNonNull(constants$8.X509_STORE_CTX_get0_current_issuer$MH,"X509_STORE_CTX_get0_current_issuer");
    }
    public static MemorySegment X509_STORE_CTX_get0_current_issuer ( MemorySegment ctx) {
        var mh$ = X509_STORE_CTX_get0_current_issuer$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle d2i_X509_bio$MH() {
        return RuntimeHelper.requireNonNull(constants$8.d2i_X509_bio$MH,"d2i_X509_bio");
    }
    public static MemorySegment d2i_X509_bio ( MemorySegment bp,  MemorySegment x509) {
        var mh$ = d2i_X509_bio$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bp, x509);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_free$MH() {
        return RuntimeHelper.requireNonNull(constants$8.X509_free$MH,"X509_free");
    }
    public static void X509_free ( MemorySegment a) {
        var mh$ = X509_free$MH();
        try {
            mh$.invokeExact(a);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle d2i_X509$MH() {
        return RuntimeHelper.requireNonNull(constants$9.d2i_X509$MH,"d2i_X509");
    }
    public static MemorySegment d2i_X509 ( MemorySegment a,  MemorySegment in,  long len) {
        var mh$ = d2i_X509$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(a, in, len);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle i2d_X509$MH() {
        return RuntimeHelper.requireNonNull(constants$9.i2d_X509$MH,"i2d_X509");
    }
    public static int i2d_X509 ( MemorySegment a,  MemorySegment out) {
        var mh$ = i2d_X509$MH();
        try {
            return (int)mh$.invokeExact(a, out);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_get_ext_by_NID$MH() {
        return RuntimeHelper.requireNonNull(constants$9.X509_get_ext_by_NID$MH,"X509_get_ext_by_NID");
    }
    public static int X509_get_ext_by_NID ( MemorySegment x,  int nid,  int lastpos) {
        var mh$ = X509_get_ext_by_NID$MH();
        try {
            return (int)mh$.invokeExact(x, nid, lastpos);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_get_ext$MH() {
        return RuntimeHelper.requireNonNull(constants$9.X509_get_ext$MH,"X509_get_ext");
    }
    public static MemorySegment X509_get_ext ( MemorySegment x,  int loc) {
        var mh$ = X509_get_ext$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(x, loc);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_EXTENSION_get_data$MH() {
        return RuntimeHelper.requireNonNull(constants$9.X509_EXTENSION_get_data$MH,"X509_EXTENSION_get_data");
    }
    public static MemorySegment X509_EXTENSION_get_data ( MemorySegment ne) {
        var mh$ = X509_EXTENSION_get_data$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(ne);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle PEM_read_bio_X509_AUX$MH() {
        return RuntimeHelper.requireNonNull(constants$9.PEM_read_bio_X509_AUX$MH,"PEM_read_bio_X509_AUX");
    }
    public static MemorySegment PEM_read_bio_X509_AUX ( MemorySegment out,  MemorySegment x,  MemorySegment cb,  MemorySegment u) {
        var mh$ = PEM_read_bio_X509_AUX$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(out, x, cb, u);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle PEM_read_bio_ECPKParameters$MH() {
        return RuntimeHelper.requireNonNull(constants$10.PEM_read_bio_ECPKParameters$MH,"PEM_read_bio_ECPKParameters");
    }
    public static MemorySegment PEM_read_bio_ECPKParameters ( MemorySegment out,  MemorySegment x,  MemorySegment cb,  MemorySegment u) {
        var mh$ = PEM_read_bio_ECPKParameters$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(out, x, cb, u);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle PEM_read_bio_DHparams$MH() {
        return RuntimeHelper.requireNonNull(constants$10.PEM_read_bio_DHparams$MH,"PEM_read_bio_DHparams");
    }
    public static MemorySegment PEM_read_bio_DHparams ( MemorySegment out,  MemorySegment x,  MemorySegment cb,  MemorySegment u) {
        var mh$ = PEM_read_bio_DHparams$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(out, x, cb, u);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle PEM_read_bio_PrivateKey$MH() {
        return RuntimeHelper.requireNonNull(constants$10.PEM_read_bio_PrivateKey$MH,"PEM_read_bio_PrivateKey");
    }
    public static MemorySegment PEM_read_bio_PrivateKey ( MemorySegment out,  MemorySegment x,  MemorySegment cb,  MemorySegment u) {
        var mh$ = PEM_read_bio_PrivateKey$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(out, x, cb, u);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_get_options$MH() {
        return RuntimeHelper.requireNonNull(constants$10.SSL_CTX_get_options$MH,"SSL_CTX_get_options");
    }
    public static long SSL_CTX_get_options ( MemorySegment ctx) {
        var mh$ = SSL_CTX_get_options$MH();
        try {
            return (long)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get_options$MH() {
        return RuntimeHelper.requireNonNull(constants$10.SSL_get_options$MH,"SSL_get_options");
    }
    public static long SSL_get_options ( MemorySegment s) {
        var mh$ = SSL_get_options$MH();
        try {
            return (long)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_clear_options$MH() {
        return RuntimeHelper.requireNonNull(constants$10.SSL_CTX_clear_options$MH,"SSL_CTX_clear_options");
    }
    public static long SSL_CTX_clear_options ( MemorySegment ctx,  long op) {
        var mh$ = SSL_CTX_clear_options$MH();
        try {
            return (long)mh$.invokeExact(ctx, op);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_options$MH() {
        return RuntimeHelper.requireNonNull(constants$11.SSL_CTX_set_options$MH,"SSL_CTX_set_options");
    }
    public static long SSL_CTX_set_options ( MemorySegment ctx,  long op) {
        var mh$ = SSL_CTX_set_options$MH();
        try {
            return (long)mh$.invokeExact(ctx, op);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_set_options$MH() {
        return RuntimeHelper.requireNonNull(constants$11.SSL_set_options$MH,"SSL_set_options");
    }
    public static long SSL_set_options ( MemorySegment s,  long op) {
        var mh$ = SSL_set_options$MH();
        try {
            return (long)mh$.invokeExact(s, op);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_alpn_select_cb$MH() {
        return RuntimeHelper.requireNonNull(constants$11.SSL_CTX_set_alpn_select_cb$MH,"SSL_CTX_set_alpn_select_cb");
    }
    public static void SSL_CTX_set_alpn_select_cb ( MemorySegment ctx,  MemorySegment cb,  MemorySegment arg) {
        var mh$ = SSL_CTX_set_alpn_select_cb$MH();
        try {
            mh$.invokeExact(ctx, cb, arg);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get0_alpn_selected$MH() {
        return RuntimeHelper.requireNonNull(constants$11.SSL_get0_alpn_selected$MH,"SSL_get0_alpn_selected");
    }
    public static void SSL_get0_alpn_selected ( MemorySegment ssl,  MemorySegment data,  MemorySegment len) {
        var mh$ = SSL_get0_alpn_selected$MH();
        try {
            mh$.invokeExact(ssl, data, len);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_in_init$MH() {
        return RuntimeHelper.requireNonNull(constants$11.SSL_in_init$MH,"SSL_in_init");
    }
    public static int SSL_in_init ( MemorySegment s) {
        var mh$ = SSL_in_init$MH();
        try {
            return (int)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_cipher_list$MH() {
        return RuntimeHelper.requireNonNull(constants$11.SSL_CTX_set_cipher_list$MH,"SSL_CTX_set_cipher_list");
    }
    public static int SSL_CTX_set_cipher_list ( MemorySegment x0,  MemorySegment str) {
        var mh$ = SSL_CTX_set_cipher_list$MH();
        try {
            return (int)mh$.invokeExact(x0, str);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_new$MH() {
        return RuntimeHelper.requireNonNull(constants$12.SSL_CTX_new$MH,"SSL_CTX_new");
    }
    public static MemorySegment SSL_CTX_new ( MemorySegment meth) {
        var mh$ = SSL_CTX_new$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(meth);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_free$MH() {
        return RuntimeHelper.requireNonNull(constants$12.SSL_CTX_free$MH,"SSL_CTX_free");
    }
    public static void SSL_CTX_free ( MemorySegment x0) {
        var mh$ = SSL_CTX_free$MH();
        try {
            mh$.invokeExact(x0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_timeout$MH() {
        return RuntimeHelper.requireNonNull(constants$12.SSL_CTX_set_timeout$MH,"SSL_CTX_set_timeout");
    }
    public static long SSL_CTX_set_timeout ( MemorySegment ctx,  long t) {
        var mh$ = SSL_CTX_set_timeout$MH();
        try {
            return (long)mh$.invokeExact(ctx, t);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_get_timeout$MH() {
        return RuntimeHelper.requireNonNull(constants$12.SSL_CTX_get_timeout$MH,"SSL_CTX_get_timeout");
    }
    public static long SSL_CTX_get_timeout ( MemorySegment ctx) {
        var mh$ = SSL_CTX_get_timeout$MH();
        try {
            return (long)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_get_cert_store$MH() {
        return RuntimeHelper.requireNonNull(constants$12.SSL_CTX_get_cert_store$MH,"SSL_CTX_get_cert_store");
    }
    public static MemorySegment SSL_CTX_get_cert_store ( MemorySegment x0) {
        var mh$ = SSL_CTX_get_cert_store$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(x0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get_current_cipher$MH() {
        return RuntimeHelper.requireNonNull(constants$12.SSL_get_current_cipher$MH,"SSL_get_current_cipher");
    }
    public static MemorySegment SSL_get_current_cipher ( MemorySegment s) {
        var mh$ = SSL_get_current_cipher$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CIPHER_get_name$MH() {
        return RuntimeHelper.requireNonNull(constants$13.SSL_CIPHER_get_name$MH,"SSL_CIPHER_get_name");
    }
    public static MemorySegment SSL_CIPHER_get_name ( MemorySegment c) {
        var mh$ = SSL_CIPHER_get_name$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(c);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CIPHER_get_kx_nid$MH() {
        return RuntimeHelper.requireNonNull(constants$13.SSL_CIPHER_get_kx_nid$MH,"SSL_CIPHER_get_kx_nid");
    }
    public static int SSL_CIPHER_get_kx_nid ( MemorySegment c) {
        var mh$ = SSL_CIPHER_get_kx_nid$MH();
        try {
            return (int)mh$.invokeExact(c);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CIPHER_get_auth_nid$MH() {
        return RuntimeHelper.requireNonNull(constants$13.SSL_CIPHER_get_auth_nid$MH,"SSL_CIPHER_get_auth_nid");
    }
    public static int SSL_CIPHER_get_auth_nid ( MemorySegment c) {
        var mh$ = SSL_CIPHER_get_auth_nid$MH();
        try {
            return (int)mh$.invokeExact(c);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_pending$MH() {
        return RuntimeHelper.requireNonNull(constants$13.SSL_pending$MH,"SSL_pending");
    }
    public static int SSL_pending ( MemorySegment s) {
        var mh$ = SSL_pending$MH();
        try {
            return (int)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_set_bio$MH() {
        return RuntimeHelper.requireNonNull(constants$13.SSL_set_bio$MH,"SSL_set_bio");
    }
    public static void SSL_set_bio ( MemorySegment s,  MemorySegment rbio,  MemorySegment wbio) {
        var mh$ = SSL_set_bio$MH();
        try {
            mh$.invokeExact(s, rbio, wbio);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_set_cipher_list$MH() {
        return RuntimeHelper.requireNonNull(constants$13.SSL_set_cipher_list$MH,"SSL_set_cipher_list");
    }
    public static int SSL_set_cipher_list ( MemorySegment s,  MemorySegment str) {
        var mh$ = SSL_set_cipher_list$MH();
        try {
            return (int)mh$.invokeExact(s, str);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_ciphersuites$MH() {
        return RuntimeHelper.requireNonNull(constants$14.SSL_CTX_set_ciphersuites$MH,"SSL_CTX_set_ciphersuites");
    }
    public static int SSL_CTX_set_ciphersuites ( MemorySegment ctx,  MemorySegment str) {
        var mh$ = SSL_CTX_set_ciphersuites$MH();
        try {
            return (int)mh$.invokeExact(ctx, str);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_set_verify$MH() {
        return RuntimeHelper.requireNonNull(constants$14.SSL_set_verify$MH,"SSL_set_verify");
    }
    public static void SSL_set_verify ( MemorySegment s,  int mode,  MemorySegment callback) {
        var mh$ = SSL_set_verify$MH();
        try {
            mh$.invokeExact(s, mode, callback);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_use_certificate_chain_file$MH() {
        return RuntimeHelper.requireNonNull(constants$14.SSL_CTX_use_certificate_chain_file$MH,"SSL_CTX_use_certificate_chain_file");
    }
    public static int SSL_CTX_use_certificate_chain_file ( MemorySegment ctx,  MemorySegment file) {
        var mh$ = SSL_CTX_use_certificate_chain_file$MH();
        try {
            return (int)mh$.invokeExact(ctx, file);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_load_client_CA_file$MH() {
        return RuntimeHelper.requireNonNull(constants$14.SSL_load_client_CA_file$MH,"SSL_load_client_CA_file");
    }
    public static MemorySegment SSL_load_client_CA_file ( MemorySegment file) {
        var mh$ = SSL_load_client_CA_file$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(file);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_add_file_cert_subjects_to_stack$MH() {
        return RuntimeHelper.requireNonNull(constants$14.SSL_add_file_cert_subjects_to_stack$MH,"SSL_add_file_cert_subjects_to_stack");
    }
    public static int SSL_add_file_cert_subjects_to_stack ( MemorySegment stackCAs,  MemorySegment file) {
        var mh$ = SSL_add_file_cert_subjects_to_stack$MH();
        try {
            return (int)mh$.invokeExact(stackCAs, file);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_SESSION_get_time$MH() {
        return RuntimeHelper.requireNonNull(constants$14.SSL_SESSION_get_time$MH,"SSL_SESSION_get_time");
    }
    public static long SSL_SESSION_get_time ( MemorySegment s) {
        var mh$ = SSL_SESSION_get_time$MH();
        try {
            return (long)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_SESSION_get_id$MH() {
        return RuntimeHelper.requireNonNull(constants$15.SSL_SESSION_get_id$MH,"SSL_SESSION_get_id");
    }
    public static MemorySegment SSL_SESSION_get_id ( MemorySegment s,  MemorySegment len) {
        var mh$ = SSL_SESSION_get_id$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(s, len);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get1_peer_certificate$MH() {
        return RuntimeHelper.requireNonNull(constants$15.SSL_get1_peer_certificate$MH,"SSL_get1_peer_certificate");
    }
    public static MemorySegment SSL_get1_peer_certificate ( MemorySegment s) {
        var mh$ = SSL_get1_peer_certificate$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get_peer_cert_chain$MH() {
        return RuntimeHelper.requireNonNull(constants$15.SSL_get_peer_cert_chain$MH,"SSL_get_peer_cert_chain");
    }
    public static MemorySegment SSL_get_peer_cert_chain ( MemorySegment s) {
        var mh$ = SSL_get_peer_cert_chain$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_verify$MH() {
        return RuntimeHelper.requireNonNull(constants$15.SSL_CTX_set_verify$MH,"SSL_CTX_set_verify");
    }
    public static void SSL_CTX_set_verify ( MemorySegment ctx,  int mode,  MemorySegment callback) {
        var mh$ = SSL_CTX_set_verify$MH();
        try {
            mh$.invokeExact(ctx, mode, callback);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_cert_verify_callback$MH() {
        return RuntimeHelper.requireNonNull(constants$16.SSL_CTX_set_cert_verify_callback$MH,"SSL_CTX_set_cert_verify_callback");
    }
    public static void SSL_CTX_set_cert_verify_callback ( MemorySegment ctx,  MemorySegment cb,  MemorySegment arg) {
        var mh$ = SSL_CTX_set_cert_verify_callback$MH();
        try {
            mh$.invokeExact(ctx, cb, arg);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_use_PrivateKey$MH() {
        return RuntimeHelper.requireNonNull(constants$16.SSL_CTX_use_PrivateKey$MH,"SSL_CTX_use_PrivateKey");
    }
    public static int SSL_CTX_use_PrivateKey ( MemorySegment ctx,  MemorySegment pkey) {
        var mh$ = SSL_CTX_use_PrivateKey$MH();
        try {
            return (int)mh$.invokeExact(ctx, pkey);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_use_certificate$MH() {
        return RuntimeHelper.requireNonNull(constants$16.SSL_CTX_use_certificate$MH,"SSL_CTX_use_certificate");
    }
    public static int SSL_CTX_use_certificate ( MemorySegment ctx,  MemorySegment x) {
        var mh$ = SSL_CTX_use_certificate$MH();
        try {
            return (int)mh$.invokeExact(ctx, x);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_default_passwd_cb$MH() {
        return RuntimeHelper.requireNonNull(constants$16.SSL_CTX_set_default_passwd_cb$MH,"SSL_CTX_set_default_passwd_cb");
    }
    public static void SSL_CTX_set_default_passwd_cb ( MemorySegment ctx,  MemorySegment cb) {
        var mh$ = SSL_CTX_set_default_passwd_cb$MH();
        try {
            mh$.invokeExact(ctx, cb);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_check_private_key$MH() {
        return RuntimeHelper.requireNonNull(constants$16.SSL_CTX_check_private_key$MH,"SSL_CTX_check_private_key");
    }
    public static int SSL_CTX_check_private_key ( MemorySegment ctx) {
        var mh$ = SSL_CTX_check_private_key$MH();
        try {
            return (int)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_session_id_context$MH() {
        return RuntimeHelper.requireNonNull(constants$16.SSL_CTX_set_session_id_context$MH,"SSL_CTX_set_session_id_context");
    }
    public static int SSL_CTX_set_session_id_context ( MemorySegment ctx,  MemorySegment sid_ctx,  int sid_ctx_len) {
        var mh$ = SSL_CTX_set_session_id_context$MH();
        try {
            return (int)mh$.invokeExact(ctx, sid_ctx, sid_ctx_len);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_new$MH() {
        return RuntimeHelper.requireNonNull(constants$17.SSL_new$MH,"SSL_new");
    }
    public static MemorySegment SSL_new ( MemorySegment ctx) {
        var mh$ = SSL_new$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_free$MH() {
        return RuntimeHelper.requireNonNull(constants$17.SSL_free$MH,"SSL_free");
    }
    public static void SSL_free ( MemorySegment ssl) {
        var mh$ = SSL_free$MH();
        try {
            mh$.invokeExact(ssl);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_read$MH() {
        return RuntimeHelper.requireNonNull(constants$17.SSL_read$MH,"SSL_read");
    }
    public static int SSL_read ( MemorySegment ssl,  MemorySegment buf,  int num) {
        var mh$ = SSL_read$MH();
        try {
            return (int)mh$.invokeExact(ssl, buf, num);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_write$MH() {
        return RuntimeHelper.requireNonNull(constants$17.SSL_write$MH,"SSL_write");
    }
    public static int SSL_write ( MemorySegment ssl,  MemorySegment buf,  int num) {
        var mh$ = SSL_write$MH();
        try {
            return (int)mh$.invokeExact(ssl, buf, num);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_ctrl$MH() {
        return RuntimeHelper.requireNonNull(constants$17.SSL_CTX_ctrl$MH,"SSL_CTX_ctrl");
    }
    public static long SSL_CTX_ctrl ( MemorySegment ctx,  int cmd,  long larg,  MemorySegment parg) {
        var mh$ = SSL_CTX_ctrl$MH();
        try {
            return (long)mh$.invokeExact(ctx, cmd, larg, parg);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get_version$MH() {
        return RuntimeHelper.requireNonNull(constants$17.SSL_get_version$MH,"SSL_get_version");
    }
    public static MemorySegment SSL_get_version ( MemorySegment s) {
        var mh$ = SSL_get_version$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle TLS_server_method$MH() {
        return RuntimeHelper.requireNonNull(constants$18.TLS_server_method$MH,"TLS_server_method");
    }
    public static MemorySegment TLS_server_method () {
        var mh$ = TLS_server_method$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get_ciphers$MH() {
        return RuntimeHelper.requireNonNull(constants$18.SSL_get_ciphers$MH,"SSL_get_ciphers");
    }
    public static MemorySegment SSL_get_ciphers ( MemorySegment s) {
        var mh$ = SSL_get_ciphers$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_get_ciphers$MH() {
        return RuntimeHelper.requireNonNull(constants$18.SSL_CTX_get_ciphers$MH,"SSL_CTX_get_ciphers");
    }
    public static MemorySegment SSL_CTX_get_ciphers ( MemorySegment ctx) {
        var mh$ = SSL_CTX_get_ciphers$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_do_handshake$MH() {
        return RuntimeHelper.requireNonNull(constants$18.SSL_do_handshake$MH,"SSL_do_handshake");
    }
    public static int SSL_do_handshake ( MemorySegment s) {
        var mh$ = SSL_do_handshake$MH();
        try {
            return (int)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_renegotiate$MH() {
        return RuntimeHelper.requireNonNull(constants$18.SSL_renegotiate$MH,"SSL_renegotiate");
    }
    public static int SSL_renegotiate ( MemorySegment s) {
        var mh$ = SSL_renegotiate$MH();
        try {
            return (int)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_renegotiate_pending$MH() {
        return RuntimeHelper.requireNonNull(constants$18.SSL_renegotiate_pending$MH,"SSL_renegotiate_pending");
    }
    public static int SSL_renegotiate_pending ( MemorySegment s) {
        var mh$ = SSL_renegotiate_pending$MH();
        try {
            return (int)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_shutdown$MH() {
        return RuntimeHelper.requireNonNull(constants$19.SSL_shutdown$MH,"SSL_shutdown");
    }
    public static int SSL_shutdown ( MemorySegment s) {
        var mh$ = SSL_shutdown$MH();
        try {
            return (int)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_verify_client_post_handshake$MH() {
        return RuntimeHelper.requireNonNull(constants$19.SSL_verify_client_post_handshake$MH,"SSL_verify_client_post_handshake");
    }
    public static int SSL_verify_client_post_handshake ( MemorySegment s) {
        var mh$ = SSL_verify_client_post_handshake$MH();
        try {
            return (int)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_client_CA_list$MH() {
        return RuntimeHelper.requireNonNull(constants$19.SSL_CTX_set_client_CA_list$MH,"SSL_CTX_set_client_CA_list");
    }
    public static void SSL_CTX_set_client_CA_list ( MemorySegment ctx,  MemorySegment name_list) {
        var mh$ = SSL_CTX_set_client_CA_list$MH();
        try {
            mh$.invokeExact(ctx, name_list);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_get_client_CA_list$MH() {
        return RuntimeHelper.requireNonNull(constants$19.SSL_CTX_get_client_CA_list$MH,"SSL_CTX_get_client_CA_list");
    }
    public static MemorySegment SSL_CTX_get_client_CA_list ( MemorySegment s) {
        var mh$ = SSL_CTX_get_client_CA_list$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_add_client_CA$MH() {
        return RuntimeHelper.requireNonNull(constants$19.SSL_CTX_add_client_CA$MH,"SSL_CTX_add_client_CA");
    }
    public static int SSL_CTX_add_client_CA ( MemorySegment ctx,  MemorySegment x) {
        var mh$ = SSL_CTX_add_client_CA$MH();
        try {
            return (int)mh$.invokeExact(ctx, x);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_set_connect_state$MH() {
        return RuntimeHelper.requireNonNull(constants$19.SSL_set_connect_state$MH,"SSL_set_connect_state");
    }
    public static void SSL_set_connect_state ( MemorySegment s) {
        var mh$ = SSL_set_connect_state$MH();
        try {
            mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_set_accept_state$MH() {
        return RuntimeHelper.requireNonNull(constants$20.SSL_set_accept_state$MH,"SSL_set_accept_state");
    }
    public static void SSL_set_accept_state ( MemorySegment s) {
        var mh$ = SSL_set_accept_state$MH();
        try {
            mh$.invokeExact(s);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get_privatekey$MH() {
        return RuntimeHelper.requireNonNull(constants$20.SSL_get_privatekey$MH,"SSL_get_privatekey");
    }
    public static MemorySegment SSL_get_privatekey ( MemorySegment ssl) {
        var mh$ = SSL_get_privatekey$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(ssl);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get_shutdown$MH() {
        return RuntimeHelper.requireNonNull(constants$20.SSL_get_shutdown$MH,"SSL_get_shutdown");
    }
    public static int SSL_get_shutdown ( MemorySegment ssl) {
        var mh$ = SSL_get_shutdown$MH();
        try {
            return (int)mh$.invokeExact(ssl);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_default_verify_paths$MH() {
        return RuntimeHelper.requireNonNull(constants$20.SSL_CTX_set_default_verify_paths$MH,"SSL_CTX_set_default_verify_paths");
    }
    public static int SSL_CTX_set_default_verify_paths ( MemorySegment ctx) {
        var mh$ = SSL_CTX_set_default_verify_paths$MH();
        try {
            return (int)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_load_verify_locations$MH() {
        return RuntimeHelper.requireNonNull(constants$20.SSL_CTX_load_verify_locations$MH,"SSL_CTX_load_verify_locations");
    }
    public static int SSL_CTX_load_verify_locations ( MemorySegment ctx,  MemorySegment CAfile,  MemorySegment CApath) {
        var mh$ = SSL_CTX_load_verify_locations$MH();
        try {
            return (int)mh$.invokeExact(ctx, CAfile, CApath);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get_session$MH() {
        return RuntimeHelper.requireNonNull(constants$20.SSL_get_session$MH,"SSL_get_session");
    }
    public static MemorySegment SSL_get_session ( MemorySegment ssl) {
        var mh$ = SSL_get_session$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(ssl);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_set_info_callback$MH() {
        return RuntimeHelper.requireNonNull(constants$21.SSL_set_info_callback$MH,"SSL_set_info_callback");
    }
    public static void SSL_set_info_callback ( MemorySegment ssl,  MemorySegment cb) {
        var mh$ = SSL_set_info_callback$MH();
        try {
            mh$.invokeExact(ssl, cb);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_set_verify_result$MH() {
        return RuntimeHelper.requireNonNull(constants$21.SSL_set_verify_result$MH,"SSL_set_verify_result");
    }
    public static void SSL_set_verify_result ( MemorySegment ssl,  long v) {
        var mh$ = SSL_set_verify_result$MH();
        try {
            mh$.invokeExact(ssl, v);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_get_ex_data_X509_STORE_CTX_idx$MH() {
        return RuntimeHelper.requireNonNull(constants$21.SSL_get_ex_data_X509_STORE_CTX_idx$MH,"SSL_get_ex_data_X509_STORE_CTX_idx");
    }
    public static int SSL_get_ex_data_X509_STORE_CTX_idx () {
        var mh$ = SSL_get_ex_data_X509_STORE_CTX_idx$MH();
        try {
            return (int)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CTX_set_tmp_dh_callback$MH() {
        return RuntimeHelper.requireNonNull(constants$22.SSL_CTX_set_tmp_dh_callback$MH,"SSL_CTX_set_tmp_dh_callback");
    }
    public static void SSL_CTX_set_tmp_dh_callback ( MemorySegment ctx,  MemorySegment dh) {
        var mh$ = SSL_CTX_set_tmp_dh_callback$MH();
        try {
            mh$.invokeExact(ctx, dh);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CONF_CTX_new$MH() {
        return RuntimeHelper.requireNonNull(constants$22.SSL_CONF_CTX_new$MH,"SSL_CONF_CTX_new");
    }
    public static MemorySegment SSL_CONF_CTX_new () {
        var mh$ = SSL_CONF_CTX_new$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CONF_CTX_finish$MH() {
        return RuntimeHelper.requireNonNull(constants$22.SSL_CONF_CTX_finish$MH,"SSL_CONF_CTX_finish");
    }
    public static int SSL_CONF_CTX_finish ( MemorySegment cctx) {
        var mh$ = SSL_CONF_CTX_finish$MH();
        try {
            return (int)mh$.invokeExact(cctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CONF_CTX_free$MH() {
        return RuntimeHelper.requireNonNull(constants$22.SSL_CONF_CTX_free$MH,"SSL_CONF_CTX_free");
    }
    public static void SSL_CONF_CTX_free ( MemorySegment cctx) {
        var mh$ = SSL_CONF_CTX_free$MH();
        try {
            mh$.invokeExact(cctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CONF_CTX_set_flags$MH() {
        return RuntimeHelper.requireNonNull(constants$22.SSL_CONF_CTX_set_flags$MH,"SSL_CONF_CTX_set_flags");
    }
    public static int SSL_CONF_CTX_set_flags ( MemorySegment cctx,  int flags) {
        var mh$ = SSL_CONF_CTX_set_flags$MH();
        try {
            return (int)mh$.invokeExact(cctx, flags);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CONF_CTX_set_ssl_ctx$MH() {
        return RuntimeHelper.requireNonNull(constants$23.SSL_CONF_CTX_set_ssl_ctx$MH,"SSL_CONF_CTX_set_ssl_ctx");
    }
    public static void SSL_CONF_CTX_set_ssl_ctx ( MemorySegment cctx,  MemorySegment ctx) {
        var mh$ = SSL_CONF_CTX_set_ssl_ctx$MH();
        try {
            mh$.invokeExact(cctx, ctx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CONF_cmd$MH() {
        return RuntimeHelper.requireNonNull(constants$23.SSL_CONF_cmd$MH,"SSL_CONF_cmd");
    }
    public static int SSL_CONF_cmd ( MemorySegment cctx,  MemorySegment cmd,  MemorySegment value) {
        var mh$ = SSL_CONF_cmd$MH();
        try {
            return (int)mh$.invokeExact(cctx, cmd, value);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle SSL_CONF_cmd_value_type$MH() {
        return RuntimeHelper.requireNonNull(constants$23.SSL_CONF_cmd_value_type$MH,"SSL_CONF_cmd_value_type");
    }
    public static int SSL_CONF_cmd_value_type ( MemorySegment cctx,  MemorySegment cmd) {
        var mh$ = SSL_CONF_cmd_value_type$MH();
        try {
            return (int)mh$.invokeExact(cctx, cmd);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OPENSSL_init_ssl$MH() {
        return RuntimeHelper.requireNonNull(constants$23.OPENSSL_init_ssl$MH,"OPENSSL_init_ssl");
    }
    public static int OPENSSL_init_ssl ( long opts,  MemorySegment settings) {
        var mh$ = OPENSSL_init_ssl$MH();
        try {
            return (int)mh$.invokeExact(opts, settings);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ERR_get_error$MH() {
        return RuntimeHelper.requireNonNull(constants$23.ERR_get_error$MH,"ERR_get_error");
    }
    public static long ERR_get_error () {
        var mh$ = ERR_get_error$MH();
        try {
            return (long)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ERR_peek_last_error$MH() {
        return RuntimeHelper.requireNonNull(constants$23.ERR_peek_last_error$MH,"ERR_peek_last_error");
    }
    public static long ERR_peek_last_error () {
        var mh$ = ERR_peek_last_error$MH();
        try {
            return (long)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ERR_clear_error$MH() {
        return RuntimeHelper.requireNonNull(constants$24.ERR_clear_error$MH,"ERR_clear_error");
    }
    public static void ERR_clear_error () {
        var mh$ = ERR_clear_error$MH();
        try {
            mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ERR_error_string$MH() {
        return RuntimeHelper.requireNonNull(constants$24.ERR_error_string$MH,"ERR_error_string");
    }
    public static MemorySegment ERR_error_string ( long e,  MemorySegment buf) {
        var mh$ = ERR_error_string$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(e, buf);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle PKCS12_verify_mac$MH() {
        return RuntimeHelper.requireNonNull(constants$24.PKCS12_verify_mac$MH,"PKCS12_verify_mac");
    }
    public static int PKCS12_verify_mac ( MemorySegment p12,  MemorySegment pass,  int passlen) {
        var mh$ = PKCS12_verify_mac$MH();
        try {
            return (int)mh$.invokeExact(p12, pass, passlen);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle PKCS12_free$MH() {
        return RuntimeHelper.requireNonNull(constants$24.PKCS12_free$MH,"PKCS12_free");
    }
    public static void PKCS12_free ( MemorySegment a) {
        var mh$ = PKCS12_free$MH();
        try {
            mh$.invokeExact(a);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle PKCS12_parse$MH() {
        return RuntimeHelper.requireNonNull(constants$24.PKCS12_parse$MH,"PKCS12_parse");
    }
    public static int PKCS12_parse ( MemorySegment p12,  MemorySegment pass,  MemorySegment pkey,  MemorySegment cert,  MemorySegment ca) {
        var mh$ = PKCS12_parse$MH();
        try {
            return (int)mh$.invokeExact(p12, pass, pkey, cert, ca);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle d2i_PKCS12_bio$MH() {
        return RuntimeHelper.requireNonNull(constants$24.d2i_PKCS12_bio$MH,"d2i_PKCS12_bio");
    }
    public static MemorySegment d2i_PKCS12_bio ( MemorySegment bp,  MemorySegment p12) {
        var mh$ = d2i_PKCS12_bio$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bp, p12);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle RAND_seed$MH() {
        return RuntimeHelper.requireNonNull(constants$25.RAND_seed$MH,"RAND_seed");
    }
    public static void RAND_seed ( MemorySegment buf,  int num) {
        var mh$ = RAND_seed$MH();
        try {
            mh$.invokeExact(buf, num);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle RAND_load_file$MH() {
        return RuntimeHelper.requireNonNull(constants$25.RAND_load_file$MH,"RAND_load_file");
    }
    public static int RAND_load_file ( MemorySegment file,  long max_bytes) {
        var mh$ = RAND_load_file$MH();
        try {
            return (int)mh$.invokeExact(file, max_bytes);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle X509_check_issued$MH() {
        return RuntimeHelper.requireNonNull(constants$25.X509_check_issued$MH,"X509_check_issued");
    }
    public static int X509_check_issued ( MemorySegment issuer,  MemorySegment subject) {
        var mh$ = X509_check_issued$MH();
        try {
            return (int)mh$.invokeExact(issuer, subject);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ENGINE_by_id$MH() {
        return RuntimeHelper.requireNonNull(constants$25.ENGINE_by_id$MH,"ENGINE_by_id");
    }
    public static MemorySegment ENGINE_by_id ( MemorySegment id) {
        var mh$ = ENGINE_by_id$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(id);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ENGINE_register_all_complete$MH() {
        return RuntimeHelper.requireNonNull(constants$25.ENGINE_register_all_complete$MH,"ENGINE_register_all_complete");
    }
    public static int ENGINE_register_all_complete () {
        var mh$ = ENGINE_register_all_complete$MH();
        try {
            return (int)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ENGINE_ctrl_cmd_string$MH() {
        return RuntimeHelper.requireNonNull(constants$25.ENGINE_ctrl_cmd_string$MH,"ENGINE_ctrl_cmd_string");
    }
    public static int ENGINE_ctrl_cmd_string ( MemorySegment e,  MemorySegment cmd_name,  MemorySegment arg,  int cmd_optional) {
        var mh$ = ENGINE_ctrl_cmd_string$MH();
        try {
            return (int)mh$.invokeExact(e, cmd_name, arg, cmd_optional);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ENGINE_free$MH() {
        return RuntimeHelper.requireNonNull(constants$26.ENGINE_free$MH,"ENGINE_free");
    }
    public static int ENGINE_free ( MemorySegment e) {
        var mh$ = ENGINE_free$MH();
        try {
            return (int)mh$.invokeExact(e);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ENGINE_load_private_key$MH() {
        return RuntimeHelper.requireNonNull(constants$26.ENGINE_load_private_key$MH,"ENGINE_load_private_key");
    }
    public static MemorySegment ENGINE_load_private_key ( MemorySegment e,  MemorySegment key_id,  MemorySegment ui_method,  MemorySegment callback_data) {
        var mh$ = ENGINE_load_private_key$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(e, key_id, ui_method, callback_data);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle ENGINE_set_default$MH() {
        return RuntimeHelper.requireNonNull(constants$26.ENGINE_set_default$MH,"ENGINE_set_default");
    }
    public static int ENGINE_set_default ( MemorySegment e,  int flags) {
        var mh$ = ENGINE_set_default$MH();
        try {
            return (int)mh$.invokeExact(e, flags);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_cert_to_id$MH() {
        return RuntimeHelper.requireNonNull(constants$26.OCSP_cert_to_id$MH,"OCSP_cert_to_id");
    }
    public static MemorySegment OCSP_cert_to_id ( MemorySegment dgst,  MemorySegment subject,  MemorySegment issuer) {
        var mh$ = OCSP_cert_to_id$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(dgst, subject, issuer);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_request_add0_id$MH() {
        return RuntimeHelper.requireNonNull(constants$26.OCSP_request_add0_id$MH,"OCSP_request_add0_id");
    }
    public static MemorySegment OCSP_request_add0_id ( MemorySegment req,  MemorySegment cid) {
        var mh$ = OCSP_request_add0_id$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(req, cid);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_response_status$MH() {
        return RuntimeHelper.requireNonNull(constants$26.OCSP_response_status$MH,"OCSP_response_status");
    }
    public static int OCSP_response_status ( MemorySegment resp) {
        var mh$ = OCSP_response_status$MH();
        try {
            return (int)mh$.invokeExact(resp);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_response_get1_basic$MH() {
        return RuntimeHelper.requireNonNull(constants$27.OCSP_response_get1_basic$MH,"OCSP_response_get1_basic");
    }
    public static MemorySegment OCSP_response_get1_basic ( MemorySegment resp) {
        var mh$ = OCSP_response_get1_basic$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(resp);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_resp_get0$MH() {
        return RuntimeHelper.requireNonNull(constants$27.OCSP_resp_get0$MH,"OCSP_resp_get0");
    }
    public static MemorySegment OCSP_resp_get0 ( MemorySegment bs,  int idx) {
        var mh$ = OCSP_resp_get0$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(bs, idx);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_resp_find$MH() {
        return RuntimeHelper.requireNonNull(constants$27.OCSP_resp_find$MH,"OCSP_resp_find");
    }
    public static int OCSP_resp_find ( MemorySegment bs,  MemorySegment id,  int last) {
        var mh$ = OCSP_resp_find$MH();
        try {
            return (int)mh$.invokeExact(bs, id, last);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_single_get0_status$MH() {
        return RuntimeHelper.requireNonNull(constants$27.OCSP_single_get0_status$MH,"OCSP_single_get0_status");
    }
    public static int OCSP_single_get0_status ( MemorySegment single,  MemorySegment reason,  MemorySegment revtime,  MemorySegment thisupd,  MemorySegment nextupd) {
        var mh$ = OCSP_single_get0_status$MH();
        try {
            return (int)mh$.invokeExact(single, reason, revtime, thisupd, nextupd);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_BASICRESP_free$MH() {
        return RuntimeHelper.requireNonNull(constants$27.OCSP_BASICRESP_free$MH,"OCSP_BASICRESP_free");
    }
    public static void OCSP_BASICRESP_free ( MemorySegment a) {
        var mh$ = OCSP_BASICRESP_free$MH();
        try {
            mh$.invokeExact(a);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_RESPONSE_free$MH() {
        return RuntimeHelper.requireNonNull(constants$27.OCSP_RESPONSE_free$MH,"OCSP_RESPONSE_free");
    }
    public static void OCSP_RESPONSE_free ( MemorySegment a) {
        var mh$ = OCSP_RESPONSE_free$MH();
        try {
            mh$.invokeExact(a);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle d2i_OCSP_RESPONSE$MH() {
        return RuntimeHelper.requireNonNull(constants$28.d2i_OCSP_RESPONSE$MH,"d2i_OCSP_RESPONSE");
    }
    public static MemorySegment d2i_OCSP_RESPONSE ( MemorySegment a,  MemorySegment in,  long len) {
        var mh$ = d2i_OCSP_RESPONSE$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(a, in, len);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_CERTID_free$MH() {
        return RuntimeHelper.requireNonNull(constants$28.OCSP_CERTID_free$MH,"OCSP_CERTID_free");
    }
    public static void OCSP_CERTID_free ( MemorySegment a) {
        var mh$ = OCSP_CERTID_free$MH();
        try {
            mh$.invokeExact(a);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_REQUEST_new$MH() {
        return RuntimeHelper.requireNonNull(constants$28.OCSP_REQUEST_new$MH,"OCSP_REQUEST_new");
    }
    public static MemorySegment OCSP_REQUEST_new () {
        var mh$ = OCSP_REQUEST_new$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OCSP_REQUEST_free$MH() {
        return RuntimeHelper.requireNonNull(constants$28.OCSP_REQUEST_free$MH,"OCSP_REQUEST_free");
    }
    public static void OCSP_REQUEST_free ( MemorySegment a) {
        var mh$ = OCSP_REQUEST_free$MH();
        try {
            mh$.invokeExact(a);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle i2d_OCSP_REQUEST$MH() {
        return RuntimeHelper.requireNonNull(constants$28.i2d_OCSP_REQUEST$MH,"i2d_OCSP_REQUEST");
    }
    public static int i2d_OCSP_REQUEST ( MemorySegment a,  MemorySegment out) {
        var mh$ = i2d_OCSP_REQUEST$MH();
        try {
            return (int)mh$.invokeExact(a, out);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle OSSL_PROVIDER_get0_name$MH() {
        return RuntimeHelper.requireNonNull(constants$28.OSSL_PROVIDER_get0_name$MH,"OSSL_PROVIDER_get0_name");
    }
    public static MemorySegment OSSL_PROVIDER_get0_name ( MemorySegment prov) {
        var mh$ = OSSL_PROVIDER_get0_name$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(prov);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MemorySegment OPENSSL_FILE() {
        return constants$29.OPENSSL_FILE$SEGMENT;
    }
    public static int OPENSSL_LINE() {
        return (int)49L;
    }
    public static long OPENSSL_INIT_ENGINE_ALL_BUILTIN() {
        return 30208L;
    }
    public static int EVP_PKEY_NONE() {
        return (int)0L;
    }
    public static int EVP_PKEY_RSA() {
        return (int)6L;
    }
    public static int EVP_PKEY_DSA() {
        return (int)116L;
    }
    public static long SSL_OP_NO_TICKET() {
        return 16384L;
    }
    public static long SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION() {
        return 65536L;
    }
    public static long SSL_OP_NO_COMPRESSION() {
        return 131072L;
    }
    public static long SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION() {
        return 262144L;
    }
    public static long SSL_OP_CIPHER_SERVER_PREFERENCE() {
        return 4194304L;
    }
    public static long SSL_OP_NO_SSLv3() {
        return 33554432L;
    }
    public static long SSL_OP_NO_TLSv1() {
        return 67108864L;
    }
    public static long SSL_OP_NO_TLSv1_2() {
        return 134217728L;
    }
    public static long SSL_OP_NO_TLSv1_1() {
        return 268435456L;
    }
    public static long SSL_OP_NO_TLSv1_3() {
        return 536870912L;
    }
    public static long SSL_OP_ALL() {
        return 2147485776L;
    }
    public static int ENGINE_METHOD_ALL() {
        return (int)65535L;
    }
}


