/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;

final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle("OCSP_resp_find", constants$3.const$1);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle("OCSP_single_get0_status", constants$31.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle("OCSP_BASICRESP_free", constants$7.const$0);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle("OCSP_RESPONSE_free", constants$7.const$0);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle("d2i_OCSP_RESPONSE", constants$8.const$1);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle("OCSP_CERTID_free", constants$7.const$0);
}

