/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle("DH_free", constants$7.const$0);
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT, RuntimeHelper.POINTER,
            RuntimeHelper.POINTER, RuntimeHelper.POINTER, RuntimeHelper.POINTER);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle("DH_set0_pqg", constants$9.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle("X509_STORE_set_flags", constants$4.const$5);
    static final MethodHandle const$4 =
            RuntimeHelper.downcallHandle("X509_STORE_CTX_get0_untrusted", constants$2.const$4);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle("X509_STORE_add_lookup", constants$2.const$2);
}

