/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by jextract

package org.apache.tomcat.util.openssl;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle("ENGINE_by_id", constants$2.const$4);
    static final MethodHandle const$1 =
            RuntimeHelper.downcallHandle("ENGINE_register_all_complete", constants$27.const$0);
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT, RuntimeHelper.POINTER,
            RuntimeHelper.POINTER, RuntimeHelper.POINTER, JAVA_INT);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle("ENGINE_ctrl_cmd_string", constants$32.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle("ENGINE_free", constants$0.const$0);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle("ENGINE_load_private_key", constants$13.const$4);
}

